<?php

/**
 * @file
 * Primary module hooks for Digital Climate Strike widget module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

function digital_climate_strike_widget_preprocess_page(&$variables) {
  $module_config = \Drupal::config('digital_climate_strike_widget.settings')
    ->get();
  $enabled = $module_config['enable'];
  $default = \Drupal::config('system.theme')->get('default');
  $active = \Drupal::service('theme.manager')
    ->getActiveTheme()
    ->getName();
  // Attach only on the front page
  if ($enabled && $default === $active) {
    $variables['#attached']['library'][] = 'digital_climate_strike_widget/digital_climate_strike_widget';
    $variables['#attached']['drupalSettings']['digital_climate_strike_widget'] = $module_config;
  }
}
